name: shelf_sensei
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.2
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  cupertino_icons: ^1.0.6
  another_flutter_splash_screen: ^1.2.1
  flutter_native_splash: ^2.4.1
  flutter_zoom_drawer: ^3.2.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
